apiVersion: apps/v1
kind: Deployment
metadata:
  name: karokee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karokee
  template:
    metadata:
      labels:
        app: karokee
    spec:
      containers:
      - name: karokee
        image: karokee:latest
        imagePullPolicy: Never # to use the local image and nt from dockerhub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: karokee
spec:
  type: NodePort
  selector:
    app: karokee
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007  # Exposes service on port 30007